commit
shiotani0011/manageboy pull request #9
Opened 2021-03-07 05:58 UTC by shiotani0011

がっつりコピペなんですけど、これはこういうものくらいの認識で大丈夫なんでしょうか？

2021-03-07 06:02 UTC, TakehiroTada commented
確認しますー
PRのタイトルに作業した内容を書いていただけますとよりGOODです

2021-03-07 06:16 UTC, TakehiroTada requested changes
@shiotani0011 
みたところ `/api/auth/register` のエンドポイントで登録されるようになっていないので
修正おねがいしまーす

2021-03-07 15:31 UTC, TakehiroTada commented
みましたー　JWTのインストールのところまでですかね
ログインしたらトークンが返ってくるようにしてもらえると助かります

2021-03-08 06:20 UTC, shiotani0011 commented
https://github.com/shiotani0011/manageboy/commit/55fa38802ddf7f5b758ad78230735d25c326e1b4
修正しました、こんな感じで大丈夫そうでしょうか

2021-03-09 15:30 UTC, merged